version: '3.8'

services:
  # Development setup
  frontend-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5002
      - REACT_APP_AGENT_NAME=SQL Agent (Docker Dev)
      - REACT_APP_AGENT_TYPE=database assistant
      - REACT_APP_WELCOME_TITLE=Welcome to SQL Agent! (Docker Development)
      - REACT_APP_WELCOME_MESSAGE=Ask me anything about your database or write SQL queries. Running in Docker development mode!
      - REACT_APP_INPUT_PLACEHOLDER=Ask about your database or write a SQL query...
    networks:
      - agent-network

  # Production build
  frontend-prod:
    build:
      context: .
      target: production
      args:
        - REACT_APP_API_URL=https://your-backend-api.com
        - REACT_APP_AGENT_NAME=SQL Agent
        - REACT_APP_AGENT_TYPE=database assistant
        - REACT_APP_WELCOME_TITLE=Welcome to SQL Agent!
        - REACT_APP_WELCOME_MESSAGE=Ask me anything about your database or write SQL queries. I'm here to help!
        - REACT_APP_INPUT_PLACEHOLDER=Ask about your database or write a SQL query...
    ports:
      - "8080:80"
    networks:
      - agent-network

  # Code Assistant variant
  code-assistant:
    build:
      context: .
      target: development
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5003
      - REACT_APP_AGENT_NAME=Code Assistant
      - REACT_APP_AGENT_TYPE=coding assistant
      - REACT_APP_WELCOME_TITLE=Welcome to Code Assistant!
      - REACT_APP_WELCOME_MESSAGE=I can help you with coding questions, debugging, and writing better code!
      - REACT_APP_INPUT_PLACEHOLDER=Ask me about coding, debugging, or software development...
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
